DROP TABLE IF EXISTS COINDESK;

CREATE TABLE COINDESK (
    COIN_CODE VARCHAR(250) NOT NULL PRIMARY KEY ,
    COIN_RATE DECIMAL(10, 4) ,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP
);

DROP TABLE IF EXISTS COINDESKMAP;

CREATE TABLE COINDESKMAP (
    COIN_CODE VARCHAR(250) NOT NULL PRIMARY KEY ,
    COIN_NAME VARCHAR(250) NOT NULL ,
    COIN_RATE DECIMAL(10, 4) ,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP
);

